<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
	xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
	xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
	xmlns:tns="http://xmlns.vs.nl/fuse/demo/xsd/AnimalOrders"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
	xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
	xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
	xmlns:ns0="http://xmlns.vs.nl/fuse/demo/xsd/animalquotes"
	xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
	xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
	xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl">
	<oracle-xsl-mapper:schema>
		<!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
		<oracle-xsl-mapper:mapSources>
			<oracle-xsl-mapper:source type="WSDL">
				<oracle-xsl-mapper:schema
					location="../Schemas/AnimalQuotes.xsd" />
				<oracle-xsl-mapper:rootElement
					name="animalQuoteResponse"
					namespace="http://xmlns.vs.nl/fuse/demo/xsd/animalquotes" />
			</oracle-xsl-mapper:source>
		</oracle-xsl-mapper:mapSources>
		<oracle-xsl-mapper:mapTargets>
			<oracle-xsl-mapper:target type="XSD">
				<oracle-xsl-mapper:schema
					location="../Schemas/AnimalOrders.xsd" />
				<oracle-xsl-mapper:rootElement
					name="animalOrderResponse"
					namespace="http://xmlns.vs.nl/fuse/demo/xsd/AnimalOrders" />
			</oracle-xsl-mapper:target>
		</oracle-xsl-mapper:mapTargets>
		<!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) 
			AT [THU NOV 26 15:29:34 CET 2020]. -->
	</oracle-xsl-mapper:schema>
	<!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE -->
	<xsl:param name="quantity" />
	<xsl:template match="/">
		<xsl:variable name="quantityInStock"
			select="/ns0:animalQuoteResponse/ns0:animalQuote/ns0:quantityInStock" />
		<xsl:variable name="actualQuantity">
			<xsl:choose>
				<xsl:when test="$quantityInStock &lt; $quantity">
					<xsl:value-of select="$quantityInStock" />
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="$quantity" />
				</xsl:otherwise>
			</xsl:choose>
		</xsl:variable>
		<tns:animalOrderResponse>
			<tns:animalOrder>
				<tns:orderlines>
					<tns:orderline>
						<tns:article
							id="{/ns0:animalQuoteResponse/ns0:animalQuote/ns0:animal/ns0:id}">
							<tns:description>
								<xsl:value-of
									select="concat (/ns0:animalQuoteResponse/ns0:animalQuote/ns0:animal/ns0:name, ' - ', /ns0:animalQuoteResponse/ns0:animalQuote/ns0:animal/ns0:countryOfOrigin,', ordered quantity: ', $quantity, ', quantity in stock: ', $quantityInStock, ', actual quantity: ', $actualQuantity )" />
							</tns:description>
						</tns:article>
						<tns:quantity>
							<xsl:value-of select="$actualQuantity" />
						</tns:quantity>
						<tns:totalPrice>
							<xsl:value-of
								select="/ns0:animalQuoteResponse/ns0:animalQuote/ns0:price * $actualQuantity" />
						</tns:totalPrice>
					</tns:orderline>
				</tns:orderlines>
			</tns:animalOrder>
		</tns:animalOrderResponse>
	</xsl:template>
</xsl:stylesheet>
