<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:anor="http://xmlns.vs.nl/fuse/demo/xsd/AnimalOrders" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.vs.nl/fuse/demo/xsd/animalquotes"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../Schemas/AnimalOrders.xsd"/>
        <oracle-xsl-mapper:rootElement name="animalOrderRequest"
                                       namespace="http://xmlns.vs.nl/fuse/demo/xsd/AnimalOrders"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/AnimalQuotes.xsd"/>
        <oracle-xsl-mapper:rootElement name="animalQuoteRequest"
                                       namespace="http://xmlns.vs.nl/fuse/demo/xsd/animalquotes"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED NOV 25 12:05:27 CET 2020].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="articleId"/>
  <xsl:template match="/">
    <tns:animalQuoteRequest>
      <tns:animalId>
        <xsl:value-of select="$articleId"/>
      </tns:animalId>
      <tns:quantity>
        <xsl:value-of select="/anor:animalOrderRequest/anor:animalOrder/anor:orderlines/anor:orderline/anor:article[@id=$articleId]/../anor:quantity"/>
      </tns:quantity>
    </tns:animalQuoteRequest>
  </xsl:template>
</xsl:stylesheet>
